// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SiagroB1.Infra.Context;

#nullable disable

namespace SiagroB1.Migrations.CommonContext
{
    [DbContext(typeof(CommonDbContext))]
    [Migration("20260518142803_CreateTableProfiles")]
    partial class CreateTableProfiles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SiagroB1.Domain.Entities.Common.Company", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("VARCHAR(4) NOT NULL");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100) NOT NULL");

                    b.Property<string>("ConnectionString")
                        .IsRequired()
                        .HasColumnType("VARCHAR(200) NOT NULL");

                    b.Property<string>("SapCompanyDb")
                        .HasColumnType("VARCHAR(100) NOT NULL");

                    b.HasKey("Code");

                    b.ToTable("COMPANIES");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.Common.MenuItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<bool>("Expanded")
                        .HasColumnType("bit");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("Key")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("MENU_ITEMS");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.Common.Permission", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("VARCHAR(50) NOT NULL");

                    b.Property<string>("Description")
                        .HasColumnType("VARCHAR(100) NOT NULL");

                    b.HasKey("Code");

                    b.ToTable("PERMISSIONS");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.Common.Profile", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("Description")
                        .HasColumnType("VARCHAR(254)");

                    b.HasKey("Code");

                    b.ToTable("PROFILES");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.Common.ProfileRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProfileCode")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("RoleCode")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.HasKey("Id");

                    b.HasIndex("RoleCode");

                    b.HasIndex("ProfileCode", "RoleCode")
                        .IsUnique();

                    b.ToTable("PROFILES_ROLES");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.Common.Role", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("VARCHAR(50) NOT NULL");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Code");

                    b.ToTable("ROLES");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.Common.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("VARCHAR(256)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("USERS");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.Common.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProfileCode")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProfileCode");

                    b.HasIndex("UserId", "ProfileCode")
                        .IsUnique();

                    b.ToTable("USERS_PROFILES");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.Common.UserSession", b =>
                {
                    b.Property<string>("SessionId")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("BranchCode")
                        .IsRequired()
                        .HasColumnType("VARCHAR(14)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("IpAddress")
                        .HasColumnType("VARCHAR(45)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastActivityAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserAgent")
                        .HasColumnType("VARCHAR(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SessionId");

                    b.HasIndex("UserId");

                    b.ToTable("USER_SESSIONS");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.Common.MenuItem", b =>
                {
                    b.HasOne("SiagroB1.Domain.Entities.Common.MenuItem", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.Common.ProfileRole", b =>
                {
                    b.HasOne("SiagroB1.Domain.Entities.Common.Profile", "Profile")
                        .WithMany("Roles")
                        .HasForeignKey("ProfileCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SiagroB1.Domain.Entities.Common.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.Common.UserProfile", b =>
                {
                    b.HasOne("SiagroB1.Domain.Entities.Common.Profile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SiagroB1.Domain.Entities.Common.User", "User")
                        .WithMany("Profiles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.Common.UserSession", b =>
                {
                    b.HasOne("SiagroB1.Domain.Entities.Common.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.Common.MenuItem", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.Common.Profile", b =>
                {
                    b.Navigation("Roles");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.Common.User", b =>
                {
                    b.Navigation("Profiles");
                });
#pragma warning restore 612, 618
        }
    }
}
