// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SiagroB1.Infra.Context;

#nullable disable

namespace SiagroB1.Migrations.CommonContext
{
    [DbContext(typeof(CommonDbContext))]
    partial class CommonDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SiagroB1.Domain.Entities.Common.Company", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("VARCHAR(4) NOT NULL");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100) NOT NULL");

                    b.Property<string>("ConnectionString")
                        .IsRequired()
                        .HasColumnType("VARCHAR(200) NOT NULL");

                    b.Property<string>("SapCompanyDb")
                        .HasColumnType("VARCHAR(100) NOT NULL");

                    b.HasKey("Code");

                    b.ToTable("COMPANIES");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.Common.MenuItem", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("VARCHAR(50) NOT NULL");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<bool>("Expanded")
                        .HasColumnType("bit");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("ParentKey")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100) NOT NULL");

                    b.HasKey("Key");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("ParentKey");

                    b.ToTable("MENU_ITEMS");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.Common.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RequestIp")
                        .HasColumnType("VARCHAR(45)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("VARCHAR(64)");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash");

                    b.HasIndex("UserId");

                    b.ToTable("PASSWORD_RESET_TOKENS");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.Common.Permission", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("VARCHAR(50) NOT NULL");

                    b.Property<string>("Description")
                        .HasColumnType("VARCHAR(100) NOT NULL");

                    b.HasKey("Code");

                    b.ToTable("PERMISSIONS");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.Common.Profile", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("Description")
                        .HasColumnType("VARCHAR(254)");

                    b.HasKey("Code");

                    b.ToTable("PROFILES");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.Common.ProfileRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProfileCode")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("RoleCode")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.HasKey("Id");

                    b.HasIndex("RoleCode");

                    b.HasIndex("ProfileCode", "RoleCode")
                        .IsUnique()
                        .HasFilter("[ProfileCode] IS NOT NULL");

                    b.ToTable("PROFILES_ROLES");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.Common.Role", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("VARCHAR(50) NOT NULL");

                    b.Property<string>("Description")
                        .HasColumnType("VARCHAR(100)");

                    b.HasKey("Code");

                    b.ToTable("ROLES");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.Common.RoleMenu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MenuItemKey")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("RoleCode")
                        .HasColumnType("VARCHAR(50)");

                    b.HasKey("Id");

                    b.HasIndex("MenuItemKey");

                    b.HasIndex("RoleCode");

                    b.ToTable("ROLE_MENUS");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.Common.RolePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PermissionCode")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("RoleCode")
                        .HasColumnType("VARCHAR(50)");

                    b.HasKey("Id");

                    b.HasIndex("PermissionCode");

                    b.HasIndex("RoleCode", "PermissionCode")
                        .IsUnique()
                        .HasFilter("[RoleCode] IS NOT NULL");

                    b.ToTable("ROLE_PERMISSIONS");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.Common.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("VARCHAR(256)");

                    b.Property<byte[]>("PhotoContent")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("PhotoContentType")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("Theme")
                        .HasColumnType("VARCHAR(30)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("USERS");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.Common.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProfileCode")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProfileCode");

                    b.HasIndex("UserId", "ProfileCode")
                        .IsUnique();

                    b.ToTable("USERS_PROFILES");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.Common.UserSession", b =>
                {
                    b.Property<string>("SessionId")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("BranchCode")
                        .IsRequired()
                        .HasColumnType("VARCHAR(14)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("IpAddress")
                        .HasColumnType("VARCHAR(45)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastActivityAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserAgent")
                        .HasColumnType("VARCHAR(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SessionId");

                    b.HasIndex("UserId");

                    b.ToTable("USER_SESSIONS");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.Common.MenuItem", b =>
                {
                    b.HasOne("SiagroB1.Domain.Entities.Common.MenuItem", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentKey");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.Common.PasswordResetToken", b =>
                {
                    b.HasOne("SiagroB1.Domain.Entities.Common.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.Common.ProfileRole", b =>
                {
                    b.HasOne("SiagroB1.Domain.Entities.Common.Profile", "Profile")
                        .WithMany("Roles")
                        .HasForeignKey("ProfileCode");

                    b.HasOne("SiagroB1.Domain.Entities.Common.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.Common.RoleMenu", b =>
                {
                    b.HasOne("SiagroB1.Domain.Entities.Common.MenuItem", "MenuItem")
                        .WithMany()
                        .HasForeignKey("MenuItemKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SiagroB1.Domain.Entities.Common.Role", "Role")
                        .WithMany("Menus")
                        .HasForeignKey("RoleCode");

                    b.Navigation("MenuItem");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.Common.RolePermission", b =>
                {
                    b.HasOne("SiagroB1.Domain.Entities.Common.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SiagroB1.Domain.Entities.Common.Role", "Role")
                        .WithMany("Permissions")
                        .HasForeignKey("RoleCode");

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.Common.UserProfile", b =>
                {
                    b.HasOne("SiagroB1.Domain.Entities.Common.Profile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SiagroB1.Domain.Entities.Common.User", "User")
                        .WithMany("Profiles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.Common.UserSession", b =>
                {
                    b.HasOne("SiagroB1.Domain.Entities.Common.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.Common.MenuItem", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.Common.Profile", b =>
                {
                    b.Navigation("Roles");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.Common.Role", b =>
                {
                    b.Navigation("Menus");

                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.Common.User", b =>
                {
                    b.Navigation("Profiles");
                });
#pragma warning restore 612, 618
        }
    }
}
