// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SiagroB1.Infra.Context;

#nullable disable

namespace SiagroB1.Migrations.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251106142410_CreateTableWeighingTickets")]
    partial class CreateTableWeighingTickets
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SiagroB1.Domain.Entities.Branch", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("VARCHAR(14) NOT NULL")
                        .HasColumnOrder(1);

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100) NOT NULL");

                    b.HasKey("Key");

                    b.ToTable("BRANCHS");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.HarvestSeason", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("VARCHAR(10) NOT NULL")
                        .HasColumnOrder(2);

                    b.Property<string>("BranchKey")
                        .HasColumnType("VARCHAR(14)")
                        .HasColumnOrder(1);

                    b.Property<bool>("Inactive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100) NOT NULL");

                    b.HasKey("Key");

                    b.HasIndex("BranchKey");

                    b.ToTable("HARVEST_SEASSONS");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.ProcessingCost", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("VARCHAR(10) NOT NULL")
                        .HasColumnOrder(2);

                    b.Property<string>("BranchKey")
                        .HasColumnType("VARCHAR(14)")
                        .HasColumnOrder(1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100) NOT NULL");

                    b.Property<int?>("FumigationIntervalDays")
                        .HasColumnType("int");

                    b.Property<decimal?>("FumigationPrice")
                        .HasColumnType("DECIMAL(18,8) NOT NULL");

                    b.Property<int?>("StorageBillingIntervalDays")
                        .HasColumnType("int");

                    b.Property<int?>("StorageGraceDays")
                        .HasColumnType("int");

                    b.Property<decimal?>("StoragePrice")
                        .HasColumnType("DECIMAL(18,8) NOT NULL");

                    b.Property<int?>("TechnicalLossGraceDays")
                        .HasColumnType("int");

                    b.Property<int?>("TechnicalLossIntervalDays")
                        .HasColumnType("int");

                    b.Property<decimal?>("TechnicalLossRate")
                        .HasColumnType("DECIMAL(18,8) NOT NULL");

                    b.HasKey("Key");

                    b.HasIndex("BranchKey");

                    b.ToTable("PROCESSING_COSTS");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.ProcessingCostDryingDetail", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<decimal?>("FinalMoisture")
                        .HasColumnType("DECIMAL(18,1) DEFAULT 0");

                    b.Property<decimal?>("InitialMoisture")
                        .HasColumnType("DECIMAL(18,1) DEFAULT 0");

                    b.Property<decimal?>("Price")
                        .HasColumnType("DECIMAL(18,8) DEFAULT 0");

                    b.Property<string>("ProcessingCostKey")
                        .HasColumnType("VARCHAR(10)");

                    b.HasKey("ItemId");

                    b.HasIndex("ProcessingCostKey");

                    b.ToTable("PROCESSING_COST_DRYING_DETAILS");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.ProcessingCostDryingParameter", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<decimal?>("FinalMoisture")
                        .HasColumnType("DECIMAL(18,1) DEFAULT 0");

                    b.Property<decimal?>("InitialMoisture")
                        .HasColumnType("DECIMAL(18,1) DEFAULT 0");

                    b.Property<string>("ProcessingCostKey")
                        .HasColumnType("VARCHAR(10)");

                    b.Property<decimal?>("Rate")
                        .HasColumnType("DECIMAL(18,8) DEFAULT 0");

                    b.HasKey("ItemId");

                    b.HasIndex("ProcessingCostKey");

                    b.ToTable("PROCESSING_COST_DRYING_PARAMETERS");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.ProcessingCostQualityParameter", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<decimal?>("ExcessDiscountRate")
                        .HasColumnType("DECIMAL(18,1) NOT NULL");

                    b.Property<decimal?>("MaxLimitRate")
                        .HasColumnType("DECIMAL(18,1) NOT NULL");

                    b.Property<string>("ProcessingCostKey")
                        .HasColumnType("VARCHAR(10)");

                    b.Property<string>("QualityAttribKey")
                        .IsRequired()
                        .HasColumnType("VARCHAR(10) NOT NULL");

                    b.HasKey("ItemId");

                    b.HasIndex("ProcessingCostKey");

                    b.HasIndex("QualityAttribKey");

                    b.ToTable("PROCESSING_COST_QUALITY_PARAMETERS");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.ProcessingCostServiceDetail", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<decimal>("Price")
                        .HasColumnType("DECIMAL(18,8) DEFAULT 0");

                    b.Property<string>("ProcessingCostKey")
                        .HasColumnType("VARCHAR(10)");

                    b.Property<string>("ProcessingServiceKey")
                        .HasColumnType("VARCHAR(10) NOT NULL");

                    b.HasKey("ItemId");

                    b.HasIndex("ProcessingCostKey");

                    b.HasIndex("ProcessingServiceKey");

                    b.ToTable("PROCESSING_COST_SERVICE_DETAILS");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.ProcessingService", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("VARCHAR(10) NOT NULL")
                        .HasColumnOrder(2);

                    b.Property<string>("BranchKey")
                        .HasColumnType("VARCHAR(14)")
                        .HasColumnOrder(1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100) NOT NULL");

                    b.HasKey("Key");

                    b.HasIndex("BranchKey");

                    b.ToTable("PROCESSING_SERVICES");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.QualityAttrib", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("VARCHAR(10) NOT NULL")
                        .HasColumnOrder(2);

                    b.Property<string>("BranchKey")
                        .HasColumnType("VARCHAR(14)")
                        .HasColumnOrder(1);

                    b.Property<bool>("Disabled")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100) NOT NULL");

                    b.HasKey("Key");

                    b.HasIndex("BranchKey");

                    b.ToTable("QUALITY_ATTRIBS");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.QualityInspection", b =>
                {
                    b.Property<string>("BranchKey")
                        .HasColumnType("VARCHAR(14)")
                        .HasColumnOrder(1);

                    b.Property<string>("WeighingTicketKey")
                        .HasMaxLength(10)
                        .HasColumnType("VARCHAR(10)")
                        .HasColumnOrder(2);

                    b.Property<string>("QualityAttribKey")
                        .HasMaxLength(10)
                        .HasColumnType("VARCHAR(10)")
                        .HasColumnOrder(3);

                    b.Property<decimal>("Value")
                        .HasColumnType("DECIMAL(18,1) DEFAULT 0");

                    b.HasKey("BranchKey", "WeighingTicketKey", "QualityAttribKey");

                    b.HasIndex("QualityAttribKey");

                    b.HasIndex("WeighingTicketKey");

                    b.ToTable("QUALITY_INSPECTIONS");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.State", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("VARCHAR(10) NOT NULL")
                        .HasColumnOrder(2);

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("VARCHAR(2) NOT NULL");

                    b.Property<string>("BranchKey")
                        .HasColumnType("VARCHAR(14)")
                        .HasColumnOrder(1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100) NOT NULL");

                    b.HasKey("Key");

                    b.HasIndex("BranchKey");

                    b.ToTable("STATES");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.StorageLot", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("VARCHAR(10) NOT NULL")
                        .HasColumnOrder(2);

                    b.Property<decimal>("Balance")
                        .HasColumnType("DECIMAL(18, 3) DEFAULT 0");

                    b.Property<string>("BranchKey")
                        .HasColumnType("VARCHAR(14)")
                        .HasColumnOrder(1);

                    b.Property<string>("CardCode")
                        .IsRequired()
                        .HasColumnType("VARCHAR(10) NOT NULL");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100) NOT NULL");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasColumnType("VARCHAR(10) NOT NULL");

                    b.Property<string>("ProcessingCostKey")
                        .IsRequired()
                        .HasColumnType("VARCHAR(10) NOT NULL");

                    b.Property<string>("WarehouseKey")
                        .IsRequired()
                        .HasColumnType("VARCHAR(10) NOT NULL");

                    b.HasKey("Key");

                    b.HasIndex("BranchKey");

                    b.HasIndex("ProcessingCostKey");

                    b.HasIndex("WarehouseKey");

                    b.ToTable("STORAGE_LOTS");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.Truck", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("VARCHAR(10) NOT NULL")
                        .HasColumnOrder(2);

                    b.Property<string>("BranchKey")
                        .HasColumnType("VARCHAR(14)")
                        .HasColumnOrder(1);

                    b.Property<string>("City")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("Model")
                        .HasColumnType("VARCHAR(100) NOT NULL");

                    b.Property<string>("StateKey")
                        .HasColumnType("VARCHAR(10)");

                    b.HasKey("Key");

                    b.HasIndex("BranchKey");

                    b.HasIndex("StateKey");

                    b.ToTable("TRUCKS");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.TruckDriver", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("VARCHAR(10) NOT NULL")
                        .HasColumnOrder(2);

                    b.Property<string>("BranchKey")
                        .HasColumnType("VARCHAR(14)")
                        .HasColumnOrder(1);

                    b.Property<string>("Cpf")
                        .HasColumnType("VARCHAR(11) ");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100) NOT NULL");

                    b.HasKey("Key");

                    b.HasIndex("BranchKey");

                    b.ToTable("TRUCK_DRIVERS");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.UnitOfMeasure", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("VARCHAR(10) NOT NULL")
                        .HasColumnOrder(2);

                    b.Property<string>("BranchKey")
                        .HasColumnType("VARCHAR(14)")
                        .HasColumnOrder(1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100) NOT NULL");

                    b.HasKey("Key");

                    b.HasIndex("BranchKey");

                    b.ToTable("UNITS_OF_MEASURE");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.Warehouse", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("VARCHAR(10) NOT NULL")
                        .HasColumnOrder(2);

                    b.Property<string>("BranchKey")
                        .HasColumnType("VARCHAR(14)")
                        .HasColumnOrder(1);

                    b.Property<bool>("Inactive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100) NOT NULL");

                    b.Property<string>("TaxId")
                        .HasColumnType("VARCHAR(14) NOT NULL")
                        .HasColumnName("TAXID");

                    b.HasKey("Key");

                    b.HasIndex("BranchKey");

                    b.ToTable("WAREHOUSES");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.WeighingTicket", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("VARCHAR(10) NOT NULL")
                        .HasColumnOrder(2);

                    b.Property<string>("BranchKey")
                        .HasColumnType("VARCHAR(14)")
                        .HasColumnOrder(1);

                    b.Property<string>("CardCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("VARCHAR(10) NOT NULL");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTimeOffset>("FirstWeighDateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("FirstWeighValue")
                        .HasColumnType("int");

                    b.Property<int>("GrossWeight")
                        .HasColumnType("int");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("VARCHAR(10) NOT NULL");

                    b.Property<int>("Operation")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("SecondWeighDateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("SecondWeighValue")
                        .HasColumnType("int");

                    b.Property<int>("Time")
                        .HasColumnType("int");

                    b.Property<string>("TruckDriverKey")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("VARCHAR(10) NOT NULL");

                    b.Property<string>("TruckKey")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("VARCHAR(10) NOT NULL");

                    b.HasKey("Key");

                    b.HasIndex("BranchKey");

                    b.ToTable("WEIGHTING_TICKETS");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.HarvestSeason", b =>
                {
                    b.HasOne("SiagroB1.Domain.Entities.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchKey");

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.ProcessingCost", b =>
                {
                    b.HasOne("SiagroB1.Domain.Entities.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchKey");

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.ProcessingCostDryingDetail", b =>
                {
                    b.HasOne("SiagroB1.Domain.Entities.ProcessingCost", "ProcessingCost")
                        .WithMany("DryingDetails")
                        .HasForeignKey("ProcessingCostKey");

                    b.Navigation("ProcessingCost");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.ProcessingCostDryingParameter", b =>
                {
                    b.HasOne("SiagroB1.Domain.Entities.ProcessingCost", "ProcessingCost")
                        .WithMany("DryingParameters")
                        .HasForeignKey("ProcessingCostKey");

                    b.Navigation("ProcessingCost");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.ProcessingCostQualityParameter", b =>
                {
                    b.HasOne("SiagroB1.Domain.Entities.ProcessingCost", "ProcessingCost")
                        .WithMany("QualityParameters")
                        .HasForeignKey("ProcessingCostKey");

                    b.HasOne("SiagroB1.Domain.Entities.QualityAttrib", "QualityAttrib")
                        .WithMany()
                        .HasForeignKey("QualityAttribKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcessingCost");

                    b.Navigation("QualityAttrib");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.ProcessingCostServiceDetail", b =>
                {
                    b.HasOne("SiagroB1.Domain.Entities.ProcessingCost", "ProcessingCost")
                        .WithMany("ServiceDetails")
                        .HasForeignKey("ProcessingCostKey");

                    b.HasOne("SiagroB1.Domain.Entities.ProcessingService", "ProcessingService")
                        .WithMany()
                        .HasForeignKey("ProcessingServiceKey");

                    b.Navigation("ProcessingCost");

                    b.Navigation("ProcessingService");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.ProcessingService", b =>
                {
                    b.HasOne("SiagroB1.Domain.Entities.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchKey");

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.QualityAttrib", b =>
                {
                    b.HasOne("SiagroB1.Domain.Entities.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchKey");

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.QualityInspection", b =>
                {
                    b.HasOne("SiagroB1.Domain.Entities.QualityAttrib", "QualityAttrib")
                        .WithMany()
                        .HasForeignKey("QualityAttribKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SiagroB1.Domain.Entities.WeighingTicket", "WeighingTicket")
                        .WithMany("QualityInspections")
                        .HasForeignKey("WeighingTicketKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QualityAttrib");

                    b.Navigation("WeighingTicket");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.State", b =>
                {
                    b.HasOne("SiagroB1.Domain.Entities.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchKey");

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.StorageLot", b =>
                {
                    b.HasOne("SiagroB1.Domain.Entities.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchKey");

                    b.HasOne("SiagroB1.Domain.Entities.ProcessingCost", "ProcessingCost")
                        .WithMany()
                        .HasForeignKey("ProcessingCostKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SiagroB1.Domain.Entities.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("ProcessingCost");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.Truck", b =>
                {
                    b.HasOne("SiagroB1.Domain.Entities.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchKey");

                    b.HasOne("SiagroB1.Domain.Entities.State", "State")
                        .WithMany()
                        .HasForeignKey("StateKey");

                    b.Navigation("Branch");

                    b.Navigation("State");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.TruckDriver", b =>
                {
                    b.HasOne("SiagroB1.Domain.Entities.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchKey");

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.UnitOfMeasure", b =>
                {
                    b.HasOne("SiagroB1.Domain.Entities.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchKey");

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.Warehouse", b =>
                {
                    b.HasOne("SiagroB1.Domain.Entities.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchKey");

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.WeighingTicket", b =>
                {
                    b.HasOne("SiagroB1.Domain.Entities.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchKey");

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.ProcessingCost", b =>
                {
                    b.Navigation("DryingDetails");

                    b.Navigation("DryingParameters");

                    b.Navigation("QualityParameters");

                    b.Navigation("ServiceDetails");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.WeighingTicket", b =>
                {
                    b.Navigation("QualityInspections");
                });
#pragma warning restore 612, 618
        }
    }
}
