// <auto-generated />

#nullable disable

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using SiagroB1.Infra.Context;

namespace SiagroB1.Migrations.AppContext
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251117141403_AlterTableStorageLots")]
    partial class AlterTableStorageLots
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SiagroB1.Domain.Entities.Branch", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("VARCHAR(14) NOT NULL")
                        .HasColumnOrder(1);

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100) NOT NULL");

                    b.HasKey("Key");

                    b.ToTable("BRANCHS");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.HarvestSeason", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("VARCHAR(10) NOT NULL");

                    b.Property<bool>("Inactive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100) NOT NULL");

                    b.HasKey("Code");

                    b.ToTable("HARVEST_SEASSONS");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.NumberSequence", b =>
                {
                    b.Property<Guid>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BranchKey")
                        .IsRequired()
                        .HasColumnType("VARCHAR(14) NOT NULL");

                    b.Property<int>("FirstNumber")
                        .HasColumnType("int");

                    b.Property<int>("LastNumber")
                        .HasColumnType("int");

                    b.Property<int>("NextNumber")
                        .HasColumnType("int");

                    b.Property<string>("Serie")
                        .IsRequired()
                        .HasColumnType("VARCHAR(15) NOT NULL");

                    b.Property<string>("TransactionCode")
                        .IsRequired()
                        .HasColumnType("VARCHAR(15) NOT NULL");

                    b.HasKey("Key");

                    b.HasIndex("BranchKey", "TransactionCode", "Serie")
                        .IsUnique();

                    b.ToTable("NUMBER_SEQUENCE");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.ProcessingCost", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("VARCHAR(10) NOT NULL");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100) NOT NULL");

                    b.Property<int?>("FumigationIntervalDays")
                        .HasColumnType("int");

                    b.Property<decimal?>("FumigationPrice")
                        .HasColumnType("DECIMAL(18,8) NOT NULL");

                    b.Property<int?>("StorageBillingIntervalDays")
                        .HasColumnType("int");

                    b.Property<int?>("StorageGraceDays")
                        .HasColumnType("int");

                    b.Property<decimal?>("StoragePrice")
                        .HasColumnType("DECIMAL(18,8) NOT NULL");

                    b.Property<int?>("TechnicalLossGraceDays")
                        .HasColumnType("int");

                    b.Property<int?>("TechnicalLossIntervalDays")
                        .HasColumnType("int");

                    b.Property<decimal?>("TechnicalLossRate")
                        .HasColumnType("DECIMAL(18,8) NOT NULL");

                    b.HasKey("Code");

                    b.ToTable("PROCESSING_COSTS");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.ProcessingCostDryingDetail", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<decimal?>("FinalMoisture")
                        .HasColumnType("DECIMAL(18,1) DEFAULT 0");

                    b.Property<decimal?>("InitialMoisture")
                        .HasColumnType("DECIMAL(18,1) DEFAULT 0");

                    b.Property<decimal?>("Price")
                        .HasColumnType("DECIMAL(18,8) DEFAULT 0");

                    b.Property<string>("ProcessingCostCode")
                        .HasColumnType("VARCHAR(10) NOT NULL");

                    b.HasKey("ItemId");

                    b.HasIndex("ProcessingCostCode");

                    b.ToTable("PROCESSING_COST_DRYING_DETAILS");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.ProcessingCostDryingParameter", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<decimal?>("FinalMoisture")
                        .HasColumnType("DECIMAL(18,1) DEFAULT 0");

                    b.Property<decimal?>("InitialMoisture")
                        .HasColumnType("DECIMAL(18,1) DEFAULT 0");

                    b.Property<string>("ProcessingCostCode")
                        .HasColumnType("VARCHAR(10) NOT NULL");

                    b.Property<decimal?>("Rate")
                        .HasColumnType("DECIMAL(18,8) DEFAULT 0");

                    b.HasKey("ItemId");

                    b.HasIndex("ProcessingCostCode");

                    b.ToTable("PROCESSING_COST_DRYING_PARAMETERS");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.ProcessingCostQualityParameter", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<decimal?>("ExcessDiscountRate")
                        .HasColumnType("DECIMAL(18,1) NOT NULL");

                    b.Property<decimal?>("MaxLimitRate")
                        .HasColumnType("DECIMAL(18,1) NOT NULL");

                    b.Property<string>("ProcessingCostCode")
                        .HasColumnType("VARCHAR(10) NOT NULL");

                    b.Property<string>("QualityAttribCode")
                        .IsRequired()
                        .HasColumnType("VARCHAR(10) NOT NULL");

                    b.HasKey("ItemId");

                    b.HasIndex("ProcessingCostCode");

                    b.HasIndex("QualityAttribCode");

                    b.ToTable("PROCESSING_COST_QUALITY_PARAMETERS");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.ProcessingCostServiceDetail", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<decimal>("Price")
                        .HasColumnType("DECIMAL(18,8) DEFAULT 0");

                    b.Property<string>("ProcessingCostCode")
                        .HasColumnType("VARCHAR(10) NOT NULL");

                    b.Property<string>("ProcessingServiceCode")
                        .IsRequired()
                        .HasColumnType("VARCHAR(10) NOT NULL");

                    b.HasKey("ItemId");

                    b.HasIndex("ProcessingCostCode");

                    b.HasIndex("ProcessingServiceCode");

                    b.ToTable("PROCESSING_COST_SERVICE_DETAILS");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.ProcessingService", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("VARCHAR(10) NOT NULL");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100) NOT NULL");

                    b.HasKey("Code");

                    b.ToTable("PROCESSING_SERVICES");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.PurchaseContract", b =>
                {
                    b.Property<Guid>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BranchKey")
                        .IsRequired()
                        .HasColumnType("VARCHAR(14)")
                        .HasColumnOrder(1);

                    b.Property<string>("BusinessParterKey")
                        .IsRequired()
                        .HasColumnType("VARCHAR(10) NOT NULL");

                    b.Property<string>("Code")
                        .HasColumnType("VARCHAR(15)");

                    b.Property<string>("Comments")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<string>("Complement")
                        .HasColumnType("VARCHAR(50) NOT NULL");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DeliveryEndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeliveryLocationCode")
                        .IsRequired()
                        .HasColumnType("VARCHAR(10) NOT NULL");

                    b.Property<DateTime>("DeliveryStartDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("FreightCost")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<int>("FreightTerms")
                        .HasColumnType("int");

                    b.Property<string>("HarvestSeasonCode")
                        .IsRequired()
                        .HasColumnType("VARCHAR(10) NOT NULL");

                    b.Property<string>("ProductKey")
                        .IsRequired()
                        .HasColumnType("VARCHAR(10) NOT NULL");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalVolume")
                        .HasColumnType("DECIMAL(18,3) DEFAULT 0");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("UnitOfMeasureKey")
                        .IsRequired()
                        .HasColumnType("VARCHAR(4) NOT NULL");

                    b.HasKey("Key");

                    b.HasIndex("BranchKey");

                    b.HasIndex("Code");

                    b.HasIndex("DeliveryLocationCode");

                    b.HasIndex("HarvestSeasonCode");

                    b.HasIndex("UnitOfMeasureKey");

                    b.ToTable("PURCHASE_CONTRACTS");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.PurchaseContractPriceFixation", b =>
                {
                    b.Property<Guid>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FixationDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("FixationPrice")
                        .HasColumnType("DECIMAL(18,8) DEFAULT 0");

                    b.Property<decimal>("FixationVolume")
                        .HasColumnType("DECIMAL(18,3) DEFAULT 0");

                    b.Property<Guid>("PurchaseContractKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Key");

                    b.HasIndex("PurchaseContractKey");

                    b.ToTable("PURCHASE_CONTRACTS_PRICE_FIXATIONS");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.PurchaseContractTax", b =>
                {
                    b.Property<Guid>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PurchaseContractKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TaxCode")
                        .IsRequired()
                        .HasColumnType("VARCHAR(5) NOT NULL");

                    b.HasKey("Key");

                    b.HasIndex("PurchaseContractKey");

                    b.HasIndex("TaxCode");

                    b.ToTable("PURCHASE_CONTRACTS_TAXES");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.QualityAttrib", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("VARCHAR(10) NOT NULL");

                    b.Property<bool>("Disabled")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100) NOT NULL");

                    b.HasKey("Code");

                    b.ToTable("QUALITY_ATTRIBS");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.QualityInspection", b =>
                {
                    b.Property<Guid>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("QualityAttribCode")
                        .IsRequired()
                        .HasColumnType("VARCHAR(10) NOT NULL");

                    b.Property<decimal>("Value")
                        .HasColumnType("DECIMAL(18,1) DEFAULT 0");

                    b.Property<Guid?>("WeighingTicketKey")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Key");

                    b.HasIndex("QualityAttribCode");

                    b.HasIndex("WeighingTicketKey");

                    b.ToTable("QUALITY_INSPECTIONS");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.State", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("VARCHAR(2) NOT NULL");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("VARCHAR(2) NOT NULL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100) NOT NULL");

                    b.HasKey("Key");

                    b.ToTable("STATES");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.StorageLot", b =>
                {
                    b.Property<Guid>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Balance")
                        .HasColumnType("DECIMAL(18, 3) DEFAULT 0");

                    b.Property<string>("BranchKey")
                        .IsRequired()
                        .HasColumnType("VARCHAR(14)")
                        .HasColumnOrder(1);

                    b.Property<string>("CardCode")
                        .IsRequired()
                        .HasColumnType("VARCHAR(10) NOT NULL");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100) NOT NULL");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasColumnType("VARCHAR(10) NOT NULL");

                    b.Property<string>("ProcessingCostCode")
                        .IsRequired()
                        .HasColumnType("VARCHAR(10) NOT NULL");

                    b.Property<string>("WarehouseCode")
                        .IsRequired()
                        .HasColumnType("VARCHAR(10) NOT NULL");

                    b.HasKey("Key");

                    b.HasIndex("BranchKey");

                    b.HasIndex("ProcessingCostCode");

                    b.HasIndex("WarehouseCode");

                    b.ToTable("STORAGE_LOTS");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.Tax", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("VARCHAR(5) NOT NULL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100) NOT NULL");

                    b.Property<decimal>("Rate")
                        .HasColumnType("DECIMAL(5,4) DEFAULT 0");

                    b.HasKey("Code");

                    b.ToTable("TAXES");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.Truck", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("VARCHAR(10) NOT NULL");

                    b.Property<string>("City")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("Model")
                        .HasColumnType("VARCHAR(100) NOT NULL");

                    b.Property<string>("StateKey")
                        .HasColumnType("VARCHAR(2)");

                    b.HasKey("Code");

                    b.HasIndex("StateKey");

                    b.ToTable("TRUCKS");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.TruckDriver", b =>
                {
                    b.Property<string>("Cpf")
                        .HasColumnType("VARCHAR(11) NOT NULL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100) NOT NULL");

                    b.HasKey("Cpf");

                    b.ToTable("TRUCK_DRIVERS");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.UnitOfMeasure", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("VARCHAR(4) NOT NULL");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100) NOT NULL");

                    b.HasKey("Code");

                    b.ToTable("UNITS_OF_MEASURE");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.Warehouse", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("VARCHAR(10) NOT NULL");

                    b.Property<bool>("Inactive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100) NOT NULL");

                    b.Property<string>("TaxId")
                        .HasColumnType("VARCHAR(14) NOT NULL")
                        .HasColumnName("TAXID");

                    b.HasKey("Code");

                    b.ToTable("WAREHOUSES");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.WeighingTicket", b =>
                {
                    b.Property<Guid>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BranchKey")
                        .IsRequired()
                        .HasColumnType("VARCHAR(14)")
                        .HasColumnOrder(1);

                    b.Property<string>("CardCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("VARCHAR(10) NOT NULL");

                    b.Property<string>("Code")
                        .HasColumnType("VARCHAR(15)");

                    b.Property<string>("Comments")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTimeOffset>("FirstWeighDateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("FirstWeighValue")
                        .HasColumnType("int");

                    b.Property<int>("GrossWeight")
                        .HasColumnType("int");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("VARCHAR(10) NOT NULL");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("ProcessigCostCode")
                        .HasColumnType("VARCHAR(10)  NOT NULL");

                    b.Property<DateTimeOffset>("SecondWeighDateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("SecondWeighValue")
                        .HasColumnType("int");

                    b.Property<int>("Time")
                        .HasColumnType("int");

                    b.Property<string>("TruckCode")
                        .IsRequired()
                        .HasColumnType("VARCHAR(10) NOT NULL");

                    b.Property<string>("TruckDriverCode")
                        .IsRequired()
                        .HasColumnType("VARCHAR(11) NOT NULL");

                    b.HasKey("Key");

                    b.HasIndex("BranchKey");

                    b.HasIndex("ProcessigCostCode");

                    b.HasIndex("TruckCode");

                    b.HasIndex("TruckDriverCode");

                    b.ToTable("WEIGHTING_TICKETS");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.NumberSequence", b =>
                {
                    b.HasOne("SiagroB1.Domain.Entities.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.ProcessingCostDryingDetail", b =>
                {
                    b.HasOne("SiagroB1.Domain.Entities.ProcessingCost", "ProcessingCost")
                        .WithMany("DryingDetails")
                        .HasForeignKey("ProcessingCostCode");

                    b.Navigation("ProcessingCost");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.ProcessingCostDryingParameter", b =>
                {
                    b.HasOne("SiagroB1.Domain.Entities.ProcessingCost", "ProcessingCost")
                        .WithMany("DryingParameters")
                        .HasForeignKey("ProcessingCostCode");

                    b.Navigation("ProcessingCost");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.ProcessingCostQualityParameter", b =>
                {
                    b.HasOne("SiagroB1.Domain.Entities.ProcessingCost", "ProcessingCost")
                        .WithMany("QualityParameters")
                        .HasForeignKey("ProcessingCostCode");

                    b.HasOne("SiagroB1.Domain.Entities.QualityAttrib", "QualityAttrib")
                        .WithMany()
                        .HasForeignKey("QualityAttribCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcessingCost");

                    b.Navigation("QualityAttrib");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.ProcessingCostServiceDetail", b =>
                {
                    b.HasOne("SiagroB1.Domain.Entities.ProcessingCost", "ProcessingCost")
                        .WithMany("ServiceDetails")
                        .HasForeignKey("ProcessingCostCode");

                    b.HasOne("SiagroB1.Domain.Entities.ProcessingService", "ProcessingService")
                        .WithMany()
                        .HasForeignKey("ProcessingServiceCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcessingCost");

                    b.Navigation("ProcessingService");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.PurchaseContract", b =>
                {
                    b.HasOne("SiagroB1.Domain.Entities.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SiagroB1.Domain.Entities.Warehouse", "DeliveryLocation")
                        .WithMany()
                        .HasForeignKey("DeliveryLocationCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SiagroB1.Domain.Entities.HarvestSeason", "HarvestSeason")
                        .WithMany()
                        .HasForeignKey("HarvestSeasonCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SiagroB1.Domain.Entities.UnitOfMeasure", "UnitOfMeasure")
                        .WithMany()
                        .HasForeignKey("UnitOfMeasureKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("DeliveryLocation");

                    b.Navigation("HarvestSeason");

                    b.Navigation("UnitOfMeasure");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.PurchaseContractPriceFixation", b =>
                {
                    b.HasOne("SiagroB1.Domain.Entities.PurchaseContract", "PurchaseContract")
                        .WithMany("PriceFixations")
                        .HasForeignKey("PurchaseContractKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PurchaseContract");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.PurchaseContractTax", b =>
                {
                    b.HasOne("SiagroB1.Domain.Entities.PurchaseContract", "PurchaseContract")
                        .WithMany("Taxes")
                        .HasForeignKey("PurchaseContractKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SiagroB1.Domain.Entities.Tax", "Tax")
                        .WithMany()
                        .HasForeignKey("TaxCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PurchaseContract");

                    b.Navigation("Tax");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.QualityInspection", b =>
                {
                    b.HasOne("SiagroB1.Domain.Entities.QualityAttrib", "QualityAttrib")
                        .WithMany()
                        .HasForeignKey("QualityAttribCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SiagroB1.Domain.Entities.WeighingTicket", "WeighingTicket")
                        .WithMany("QualityInspections")
                        .HasForeignKey("WeighingTicketKey");

                    b.Navigation("QualityAttrib");

                    b.Navigation("WeighingTicket");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.StorageLot", b =>
                {
                    b.HasOne("SiagroB1.Domain.Entities.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SiagroB1.Domain.Entities.ProcessingCost", "ProcessingCost")
                        .WithMany()
                        .HasForeignKey("ProcessingCostCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SiagroB1.Domain.Entities.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("ProcessingCost");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.Truck", b =>
                {
                    b.HasOne("SiagroB1.Domain.Entities.State", "State")
                        .WithMany()
                        .HasForeignKey("StateKey");

                    b.Navigation("State");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.WeighingTicket", b =>
                {
                    b.HasOne("SiagroB1.Domain.Entities.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SiagroB1.Domain.Entities.ProcessingCost", "ProcessingCost")
                        .WithMany()
                        .HasForeignKey("ProcessigCostCode");

                    b.HasOne("SiagroB1.Domain.Entities.Truck", "Truck")
                        .WithMany()
                        .HasForeignKey("TruckCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SiagroB1.Domain.Entities.TruckDriver", "TruckDriver")
                        .WithMany()
                        .HasForeignKey("TruckDriverCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("ProcessingCost");

                    b.Navigation("Truck");

                    b.Navigation("TruckDriver");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.ProcessingCost", b =>
                {
                    b.Navigation("DryingDetails");

                    b.Navigation("DryingParameters");

                    b.Navigation("QualityParameters");

                    b.Navigation("ServiceDetails");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.PurchaseContract", b =>
                {
                    b.Navigation("PriceFixations");

                    b.Navigation("Taxes");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.WeighingTicket", b =>
                {
                    b.Navigation("QualityInspections");
                });
#pragma warning restore 612, 618
        }
    }
}
