// <auto-generated />

#nullable disable

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using SiagroB1.Infra.Context;

namespace SiagroB1.Migrations.AppContext
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251208204124_AlterTablePurchaseContractsAlterAuditColumns")]
    partial class AlterTablePurchaseContractsAlterAuditColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SiagroB1.Domain.Entities.Agent", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("VARCHAR(10) NO NULL");

                    b.Property<bool>("Inactive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100) NOT NULL");

                    b.HasKey("Code");

                    b.ToTable("AGENTS");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.Branch", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("VARCHAR(14) NOT NULL")
                        .HasColumnOrder(1);

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100) NOT NULL");

                    b.HasKey("Code");

                    b.ToTable("BRANCHS");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.DocType", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("VARCHAR(10) NOT NULL");

                    b.Property<string>("BranchCode")
                        .HasColumnType("VARCHAR(14)")
                        .HasColumnOrder(1);

                    b.Property<int>("FirstNumber")
                        .HasColumnType("int");

                    b.Property<int>("LastNumber")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100) NOT NULL");

                    b.Property<int>("NextNumber")
                        .HasColumnType("int");

                    b.Property<string>("Serie")
                        .IsRequired()
                        .HasColumnType("VARCHAR(3) NOT NULL");

                    b.Property<int>("TransactionCode")
                        .HasColumnType("int");

                    b.HasKey("Code");

                    b.HasIndex("BranchCode");

                    b.ToTable("DOC_TYPES");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.HarvestSeason", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("VARCHAR(10) NOT NULL");

                    b.Property<bool>("Inactive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100) NOT NULL");

                    b.HasKey("Code");

                    b.ToTable("HARVEST_SEASSONS");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.LogisticRegion", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("VARCHAR(10) NOT NULL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100) NOT NULL");

                    b.HasKey("Code");

                    b.ToTable("LOGISTIC_REGIONS");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.ProcessingCost", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("VARCHAR(10) NOT NULL");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100) NOT NULL");

                    b.Property<int?>("FumigationIntervalDays")
                        .HasColumnType("int");

                    b.Property<decimal?>("FumigationPrice")
                        .HasColumnType("DECIMAL(18,8) NOT NULL");

                    b.Property<int?>("StorageBillingIntervalDays")
                        .HasColumnType("int");

                    b.Property<int?>("StorageGraceDays")
                        .HasColumnType("int");

                    b.Property<decimal?>("StoragePrice")
                        .HasColumnType("DECIMAL(18,8) NOT NULL");

                    b.Property<int?>("TechnicalLossGraceDays")
                        .HasColumnType("int");

                    b.Property<int?>("TechnicalLossIntervalDays")
                        .HasColumnType("int");

                    b.Property<decimal?>("TechnicalLossRate")
                        .HasColumnType("DECIMAL(18,8) NOT NULL");

                    b.HasKey("Code");

                    b.ToTable("PROCESSING_COSTS");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.ProcessingCostDryingDetail", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<decimal?>("FinalMoisture")
                        .HasColumnType("DECIMAL(18,1) DEFAULT 0");

                    b.Property<decimal?>("InitialMoisture")
                        .HasColumnType("DECIMAL(18,1) DEFAULT 0");

                    b.Property<decimal?>("Price")
                        .HasColumnType("DECIMAL(18,8) DEFAULT 0");

                    b.Property<string>("ProcessingCostCode")
                        .HasColumnType("VARCHAR(10) NOT NULL");

                    b.HasKey("ItemId");

                    b.HasIndex("ProcessingCostCode");

                    b.ToTable("PROCESSING_COST_DRYING_DETAILS");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.ProcessingCostDryingParameter", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<decimal?>("FinalMoisture")
                        .HasColumnType("DECIMAL(18,1) DEFAULT 0");

                    b.Property<decimal?>("InitialMoisture")
                        .HasColumnType("DECIMAL(18,1) DEFAULT 0");

                    b.Property<string>("ProcessingCostCode")
                        .HasColumnType("VARCHAR(10) NOT NULL");

                    b.Property<decimal?>("Rate")
                        .HasColumnType("DECIMAL(18,8) DEFAULT 0");

                    b.HasKey("ItemId");

                    b.HasIndex("ProcessingCostCode");

                    b.ToTable("PROCESSING_COST_DRYING_PARAMETERS");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.ProcessingCostQualityParameter", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<decimal?>("ExcessDiscountRate")
                        .HasColumnType("DECIMAL(18,1) NOT NULL");

                    b.Property<decimal?>("MaxLimitRate")
                        .HasColumnType("DECIMAL(18,1) NOT NULL");

                    b.Property<string>("ProcessingCostCode")
                        .HasColumnType("VARCHAR(10) NOT NULL");

                    b.Property<string>("QualityAttribCode")
                        .IsRequired()
                        .HasColumnType("VARCHAR(10) NOT NULL");

                    b.HasKey("ItemId");

                    b.HasIndex("ProcessingCostCode");

                    b.HasIndex("QualityAttribCode");

                    b.ToTable("PROCESSING_COST_QUALITY_PARAMETERS");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.ProcessingCostServiceDetail", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<decimal>("Price")
                        .HasColumnType("DECIMAL(18,8) DEFAULT 0");

                    b.Property<string>("ProcessingCostCode")
                        .HasColumnType("VARCHAR(10) NOT NULL");

                    b.Property<string>("ProcessingServiceCode")
                        .IsRequired()
                        .HasColumnType("VARCHAR(10) NOT NULL");

                    b.HasKey("ItemId");

                    b.HasIndex("ProcessingCostCode");

                    b.HasIndex("ProcessingServiceCode");

                    b.ToTable("PROCESSING_COST_SERVICE_DETAILS");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.ProcessingService", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("VARCHAR(10) NOT NULL");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100) NOT NULL");

                    b.HasKey("Code");

                    b.ToTable("PROCESSING_SERVICES");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.PurchaseContract", b =>
                {
                    b.Property<Guid>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AgentCode")
                        .HasColumnType("VARCHAR(10) NO NULL");

                    b.Property<string>("ApprovalComments")
                        .HasColumnType("VARCHAR(500)");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<DateTime?>("CanceledAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CanceledBy")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("CardCode")
                        .IsRequired()
                        .HasColumnType("VARCHAR(10) NOT NULL");

                    b.Property<string>("CardName")
                        .HasColumnType("VARCHAR(200) NOT NULL");

                    b.Property<string>("Code")
                        .HasColumnType("VARCHAR(50) NOT NULL");

                    b.Property<string>("Comments")
                        .HasColumnType("VARCHAR(500)");

                    b.Property<string>("Complement")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DeliveryEndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeliveryLocationCode")
                        .IsRequired()
                        .HasColumnType("VARCHAR(10) NOT NULL");

                    b.Property<DateTime>("DeliveryStartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocTypeCode")
                        .HasColumnType("VARCHAR(10)");

                    b.Property<decimal>("FreightCostStandard")
                        .HasColumnType("DECIMAL(18,8) DEFAULT 0");

                    b.Property<int>("FreightTerms")
                        .HasColumnType("int");

                    b.Property<string>("FreightUmCode")
                        .HasColumnType("VARCHAR(4) NOT NULL");

                    b.Property<string>("HarvestSeasonCode")
                        .IsRequired()
                        .HasColumnType("VARCHAR(10) NOT NULL");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasColumnType("VARCHAR(10) NOT NULL");

                    b.Property<string>("ItemName")
                        .HasColumnType("VARCHAR(200) NOT NULL");

                    b.Property<string>("LogisticRegionCode")
                        .HasColumnType("VARCHAR(10) NOT NULL");

                    b.Property<int?>("MarketType")
                        .HasColumnType("int");

                    b.Property<string>("PaymentTerms")
                        .HasColumnType("VARCHAR(500)");

                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RowId"));

                    b.Property<DateTime?>("StandardCashFlowDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("StandardCurrency")
                        .HasColumnType("int");

                    b.Property<decimal>("StandardPrice")
                        .HasColumnType("DECIMAL(18,6) DEFAULT 0");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalVolume")
                        .HasColumnType("DECIMAL(18,3) DEFAULT 0");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("UnitOfMeasureCode")
                        .IsRequired()
                        .HasColumnType("VARCHAR(4) NOT NULL");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("VARCHAR(100)");

                    b.HasKey("Key");

                    b.HasIndex("AgentCode");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("[Code] IS NOT NULL");

                    b.HasIndex("DeliveryLocationCode");

                    b.HasIndex("DocTypeCode");

                    b.HasIndex("FreightUmCode");

                    b.HasIndex("HarvestSeasonCode");

                    b.HasIndex("LogisticRegionCode");

                    b.HasIndex("UnitOfMeasureCode");

                    b.ToTable("PURCHASE_CONTRACTS");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.PurchaseContractAllocation", b =>
                {
                    b.Property<Guid>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<DateTime?>("CanceledAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CanceledBy")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<Guid>("PurchaseContractKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RowId"));

                    b.Property<Guid>("StorageTransactionKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<decimal>("Volume")
                        .HasColumnType("DECIMAL(18,3) DEFAULT 0");

                    b.HasKey("Key");

                    b.HasIndex("PurchaseContractKey");

                    b.ToTable("PURCHASE_CONTRACTS_ALLOCATIONS");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.PurchaseContractBroker", b =>
                {
                    b.Property<Guid>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CardCode")
                        .IsRequired()
                        .HasColumnType("VARCHAR(10) NOT NULL");

                    b.Property<string>("ComissionUmCode")
                        .HasColumnType("VARCHAR(4) NOT NULL");

                    b.Property<string>("Comments")
                        .HasColumnType("VARCHAR(500)");

                    b.Property<decimal>("Commission")
                        .HasColumnType("DECIMAL(18,8) DEFAULT 0");

                    b.Property<Guid?>("PurchaseContractKey")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Key");

                    b.HasIndex("ComissionUmCode");

                    b.HasIndex("PurchaseContractKey");

                    b.ToTable("PURCHASE_CONTRACTS_BROKERS");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.PurchaseContractPriceFixation", b =>
                {
                    b.Property<Guid>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("FixationDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("FixationPrice")
                        .HasColumnType("DECIMAL(18,8) DEFAULT 0");

                    b.Property<decimal>("FixationVolume")
                        .HasColumnType("DECIMAL(18,3) DEFAULT 0");

                    b.Property<decimal>("FreightCost")
                        .HasColumnType("DECIMAL(18,2) DEFAULT 0");

                    b.Property<Guid?>("PurchaseContractKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Key");

                    b.HasIndex("PurchaseContractKey");

                    b.ToTable("PURCHASE_CONTRACTS_PRICE_FIXATIONS");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.PurchaseContractQualityParameter", b =>
                {
                    b.Property<Guid>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("MaxLimitRate")
                        .HasColumnType("DECIMAL(18,1) DEFAULT 0");

                    b.Property<Guid?>("PurchaseContractKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("QualityAttribCode")
                        .IsRequired()
                        .HasColumnType("VARCHAR(10) NOT NULL");

                    b.HasKey("Key");

                    b.HasIndex("PurchaseContractKey");

                    b.HasIndex("QualityAttribCode");

                    b.ToTable("PURCHASE_CONTRACTS_QUALITY_PARAMETERS");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.PurchaseContractTax", b =>
                {
                    b.Property<Guid>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PurchaseContractKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TaxCode")
                        .IsRequired()
                        .HasColumnType("VARCHAR(15) NOT NULL");

                    b.HasKey("Key");

                    b.HasIndex("PurchaseContractKey");

                    b.HasIndex("TaxCode");

                    b.ToTable("PURCHASE_CONTRACTS_TAXES");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.QualityAttrib", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("VARCHAR(10) NOT NULL");

                    b.Property<bool>("Disabled")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100) NOT NULL");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Code");

                    b.ToTable("QUALITY_ATTRIBS");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.QualityInspection", b =>
                {
                    b.Property<Guid>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("QualityAttribCode")
                        .IsRequired()
                        .HasColumnType("VARCHAR(10) NOT NULL");

                    b.Property<decimal>("Value")
                        .HasColumnType("DECIMAL(18,1) DEFAULT 0");

                    b.Property<Guid?>("WeighingTicketKey")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Key");

                    b.HasIndex("QualityAttribCode");

                    b.HasIndex("WeighingTicketKey");

                    b.ToTable("QUALITY_INSPECTIONS");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.SalesContract", b =>
                {
                    b.Property<Guid>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AgentCode")
                        .HasColumnType("VARCHAR(10) NO NULL");

                    b.Property<string>("ApprovalComments")
                        .HasColumnType("VARCHAR(500)");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<DateTime?>("CanceledAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CanceledBy")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("CardCode")
                        .IsRequired()
                        .HasColumnType("VARCHAR(10) NOT NULL");

                    b.Property<string>("CardName")
                        .HasColumnType("VARCHAR(200)");

                    b.Property<string>("Code")
                        .HasColumnType("VARCHAR(50) NOT NULL");

                    b.Property<string>("Comments")
                        .HasColumnType("VARCHAR(500)");

                    b.Property<string>("Complement")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DeliveryEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DeliveryStartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocTypeCode")
                        .HasColumnType("VARCHAR(10) NULL");

                    b.Property<int>("FreightTerms")
                        .HasColumnType("int");

                    b.Property<string>("HarvestSeasonCode")
                        .IsRequired()
                        .HasColumnType("VARCHAR(10) NOT NULL");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasColumnType("VARCHAR(10) NOT NULL");

                    b.Property<string>("ItemName")
                        .HasColumnType("VARCHAR(200)");

                    b.Property<string>("LogisticRegionCode")
                        .HasColumnType("VARCHAR(10) NOT NULL");

                    b.Property<int?>("MarketType")
                        .HasColumnType("int");

                    b.Property<string>("PaymentTerms")
                        .HasColumnType("VARCHAR(500)");

                    b.Property<decimal>("Price")
                        .HasColumnType("DECIMAL(18,8) DEFAULT 0");

                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RowId"));

                    b.Property<DateTime?>("StandardCashFlowDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("StandardCurrency")
                        .HasColumnType("int");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalVolume")
                        .HasColumnType("DECIMAL(18,3) DEFAULT 0");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("UnitOfMeasureCode")
                        .IsRequired()
                        .HasColumnType("VARCHAR(4) NOT NULL");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<decimal>("Volume")
                        .HasColumnType("DECIMAL(18,3) DEFAULT 0");

                    b.HasKey("Key");

                    b.HasIndex("AgentCode");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("[Code] IS NOT NULL");

                    b.HasIndex("DocTypeCode");

                    b.HasIndex("HarvestSeasonCode");

                    b.HasIndex("LogisticRegionCode");

                    b.HasIndex("UnitOfMeasureCode");

                    b.ToTable("SALES_CONTRACTS");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.SalesInvoice", b =>
                {
                    b.Property<Guid>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<DateTime?>("CanceledAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CanceledBy")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("CardCode")
                        .IsRequired()
                        .HasColumnType("VARCHAR(15) NOT NULL");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<DateTime?>("InvoiceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvoiceNumber")
                        .HasColumnType("VARCHAR(9)");

                    b.Property<string>("InvoiceSeries")
                        .HasColumnType("VARCHAR(3)");

                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RowId"));

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("VARCHAR(100)");

                    b.HasKey("Key");

                    b.ToTable("SALES_INVOICES");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.SalesInvoiceItem", b =>
                {
                    b.Property<Guid>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasColumnType("VARCHAR(10) NOT NULL");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("DECIMAL(18,3) DEFAULT 0");

                    b.Property<Guid?>("SalesContractId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SalesInvoiceKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("DECIMAL(18,8) DEFAULT 0");

                    b.HasKey("Key");

                    b.HasIndex("SalesContractId");

                    b.HasIndex("SalesInvoiceKey");

                    b.ToTable("SALES_INVOICES_ITEMS");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.ShipmentRelease", b =>
                {
                    b.Property<Guid>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<decimal>("AvailableQuantity")
                        .HasColumnType("DECIMAL(18,3) DEFAULT 0");

                    b.Property<DateTime?>("CanceledAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CanceledBy")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<DateTime?>("ExpectedDeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PurchaseContractKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReleaseNumber")
                        .IsRequired()
                        .HasColumnType("VARCHAR(15) NOT NULL");

                    b.Property<decimal>("ReleasedQuantity")
                        .HasColumnType("DECIMAL(18,3) DEFAULT 0");

                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RowId"));

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("VARCHAR(100)");

                    b.HasKey("Key");

                    b.HasIndex("PurchaseContractKey");

                    b.HasIndex("ReleaseNumber")
                        .IsUnique();

                    b.ToTable("SHIPMENT_RELEASES");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.ShippingOrder", b =>
                {
                    b.Property<Guid>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<DateTime?>("CanceledAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CanceledBy")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("VARCHAR(10) NOT NULL");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasColumnType("VARCHAR(15) NOT NULL");

                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RowId"));

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("StorageAddressKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TruckCode")
                        .IsRequired()
                        .HasColumnType("VARCHAR(10) NOT NULL");

                    b.Property<string>("TruckDriverCode")
                        .IsRequired()
                        .HasColumnType("VARCHAR(11) NOT NULL");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<decimal>("Volume")
                        .HasColumnType("DECIMAL(18,3) DEFAULT 0");

                    b.HasKey("Key");

                    b.HasIndex("StorageAddressKey");

                    b.ToTable("SHIPPING_ORDERS");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.State", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("VARCHAR(2) NOT NULL");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("VARCHAR(2) NOT NULL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100) NOT NULL");

                    b.HasKey("Key");

                    b.ToTable("STATES");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.StorageAddress", b =>
                {
                    b.Property<Guid>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<DateTime?>("CanceledAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CanceledBy")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("CardCode")
                        .IsRequired()
                        .HasColumnType("VARCHAR(10) NOT NULL");

                    b.Property<string>("CardName")
                        .HasColumnType("VARCHAR(200)");

                    b.Property<string>("Code")
                        .HasColumnType("VARCHAR(50) NOT NULL");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100) NOT NULL");

                    b.Property<string>("DocTypeCode")
                        .HasColumnType("VARCHAR(10)");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasColumnType("VARCHAR(10) NOT NULL");

                    b.Property<string>("ItemName")
                        .HasColumnType("VARCHAR(200)");

                    b.Property<int>("OwnershipType")
                        .HasColumnType("int");

                    b.Property<Guid?>("PurchaseContractKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RowId"));

                    b.Property<int?>("TransactionOrigin")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("WarehouseCode")
                        .IsRequired()
                        .HasColumnType("VARCHAR(10) NOT NULL");

                    b.HasKey("Key");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("[Code] IS NOT NULL");

                    b.HasIndex("DocTypeCode");

                    b.ToTable("STORAGE_ADDRESSES");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.StorageTransaction", b =>
                {
                    b.Property<Guid>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<decimal>("AvaiableVolumeToAllocate")
                        .HasColumnType("DECIMAL(18,3) DEFAULT 0)");

                    b.Property<DateTime?>("CanceledAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CanceledBy")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("CardCode")
                        .IsRequired()
                        .HasColumnType("VARCHAR(10) NOT NULL");

                    b.Property<string>("CardName")
                        .HasColumnType("VARCHAR(200)");

                    b.Property<string>("ChaveNFe")
                        .HasColumnType("VARCHAR(44)");

                    b.Property<decimal>("CleaningDiscount")
                        .HasColumnType("decimal(18,3) DEFAULT 0");

                    b.Property<string>("Code")
                        .HasColumnType("VARCHAR(50) NOT NULL");

                    b.Property<string>("Comments")
                        .HasColumnType("VARCHAR(500)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("DocTypeCode")
                        .HasColumnType("VARCHAR(10)");

                    b.Property<decimal>("DryingDiscount")
                        .HasColumnType("decimal(18,3) DEFAULT 0");

                    b.Property<decimal>("GrossWeight")
                        .HasColumnType("decimal(18,3) DEFAULT 0");

                    b.Property<string>("InvoiceNumber")
                        .HasColumnType("VARCHAR(9)");

                    b.Property<decimal>("InvoiceQty")
                        .HasColumnType("DECIMAL(18,3) DEFAULT 0)");

                    b.Property<string>("InvoiceSerie")
                        .HasColumnType("VARCHAR(3)");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasColumnType("VARCHAR(10) NOT NULL");

                    b.Property<string>("ItemName")
                        .HasColumnType("VARCHAR(200)");

                    b.Property<decimal>("NetWeight")
                        .HasColumnType("decimal(18,3) DEFAULT 0");

                    b.Property<decimal>("OthersDicount")
                        .HasColumnType("decimal(18,3) DEFAULT 0");

                    b.Property<string>("ProcessingCostCode")
                        .HasColumnType("VARCHAR(10) NOT NULL");

                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RowId"));

                    b.Property<Guid?>("ShipmentReleaseKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ShippingOrderKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("StorageAddressKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TransactionOrigin")
                        .HasColumnType("int");

                    b.Property<int>("TransactionStatus")
                        .HasColumnType("int");

                    b.Property<string>("TransactionTime")
                        .HasColumnType("VARCHAR(20)");

                    b.Property<int>("TransactionType")
                        .HasColumnType("int");

                    b.Property<string>("TruckCode")
                        .HasColumnType("VARCHAR(10) NOT NULL");

                    b.Property<string>("TruckDriverCode")
                        .HasColumnType("VARCHAR(11) NOT NULL");

                    b.Property<string>("UnitOfMeasureCode")
                        .IsRequired()
                        .HasColumnType("VARCHAR(4) NOT NULL");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("WarehouseCode")
                        .IsRequired()
                        .HasColumnType("VARCHAR(10) NOT NULL");

                    b.Property<Guid?>("WeighingTicketKey")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Key");

                    b.HasIndex("DocTypeCode");

                    b.HasIndex("ProcessingCostCode");

                    b.HasIndex("ShipmentReleaseKey");

                    b.HasIndex("StorageAddressKey");

                    b.HasIndex("UnitOfMeasureCode");

                    b.HasIndex("WarehouseCode");

                    b.ToTable("STORAGE_TRANSACTIONS");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.StorageTransactionQualityInspection", b =>
                {
                    b.Property<Guid>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("LossValue")
                        .HasColumnType("DECIMAL(18,3) DEFAULT 0");

                    b.Property<string>("QualityAttribCode")
                        .IsRequired()
                        .HasColumnType("VARCHAR(10) NOT NULL");

                    b.Property<Guid?>("StorageTransactionKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Value")
                        .HasColumnType("DECIMAL(18,1) DEFAULT 0");

                    b.HasKey("Key");

                    b.HasIndex("QualityAttribCode");

                    b.HasIndex("StorageTransactionKey");

                    b.ToTable("STORAGE_TRANSACTIONS_QUALITY_INSPECTIONS");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.Tax", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("VARCHAR(15) NOT NULL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100) NOT NULL");

                    b.Property<decimal>("Rate")
                        .HasColumnType("DECIMAL(5,4) DEFAULT 0");

                    b.HasKey("Code");

                    b.ToTable("TAXES");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.Truck", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("VARCHAR(10) NOT NULL");

                    b.Property<string>("City")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("Model")
                        .HasColumnType("VARCHAR(100) NOT NULL");

                    b.Property<string>("StateKey")
                        .HasColumnType("VARCHAR(2)");

                    b.HasKey("Code");

                    b.HasIndex("StateKey");

                    b.ToTable("TRUCKS");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.TruckDriver", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("VARCHAR(11) NOT NULL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100) NOT NULL");

                    b.HasKey("Code");

                    b.ToTable("TRUCK_DRIVERS");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.UnitOfMeasure", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("VARCHAR(4) NOT NULL");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100) NOT NULL");

                    b.HasKey("Code");

                    b.ToTable("UNITS_OF_MEASURE");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.Warehouse", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("VARCHAR(10) NOT NULL");

                    b.Property<bool>("Inactive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100) NOT NULL");

                    b.Property<string>("TaxId")
                        .HasColumnType("VARCHAR(14) NOT NULL")
                        .HasColumnName("TAXID");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Code");

                    b.ToTable("WAREHOUSES");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.WeighingTicket", b =>
                {
                    b.Property<Guid>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<DateTime?>("CanceledAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CanceledBy")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("CardCode")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("VARCHAR(15) NOT NULL");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("VARCHAR(15) NOT NULL");

                    b.Property<string>("Comments")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTimeOffset?>("FirstWeighDateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("FirstWeighValue")
                        .HasColumnType("int");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR(50) NOT NULL");

                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RowId"));

                    b.Property<DateTimeOffset?>("SecondWeighDateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("SecondWeighValue")
                        .HasColumnType("int");

                    b.Property<int?>("Stage")
                        .HasColumnType("int");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TruckCode")
                        .IsRequired()
                        .HasColumnType("VARCHAR(10) NOT NULL");

                    b.Property<string>("TruckDriverCode")
                        .IsRequired()
                        .HasColumnType("VARCHAR(11) NOT NULL");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("VARCHAR(100)");

                    b.HasKey("Key");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("TruckCode");

                    b.HasIndex("TruckDriverCode");

                    b.ToTable("WEIGHING_TICKETS");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.DocType", b =>
                {
                    b.HasOne("SiagroB1.Domain.Entities.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchCode");

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.ProcessingCostDryingDetail", b =>
                {
                    b.HasOne("SiagroB1.Domain.Entities.ProcessingCost", "ProcessingCost")
                        .WithMany("DryingDetails")
                        .HasForeignKey("ProcessingCostCode");

                    b.Navigation("ProcessingCost");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.ProcessingCostDryingParameter", b =>
                {
                    b.HasOne("SiagroB1.Domain.Entities.ProcessingCost", "ProcessingCost")
                        .WithMany("DryingParameters")
                        .HasForeignKey("ProcessingCostCode");

                    b.Navigation("ProcessingCost");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.ProcessingCostQualityParameter", b =>
                {
                    b.HasOne("SiagroB1.Domain.Entities.ProcessingCost", "ProcessingCost")
                        .WithMany("QualityParameters")
                        .HasForeignKey("ProcessingCostCode");

                    b.HasOne("SiagroB1.Domain.Entities.QualityAttrib", "QualityAttrib")
                        .WithMany()
                        .HasForeignKey("QualityAttribCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcessingCost");

                    b.Navigation("QualityAttrib");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.ProcessingCostServiceDetail", b =>
                {
                    b.HasOne("SiagroB1.Domain.Entities.ProcessingCost", "ProcessingCost")
                        .WithMany("ServiceDetails")
                        .HasForeignKey("ProcessingCostCode");

                    b.HasOne("SiagroB1.Domain.Entities.ProcessingService", "ProcessingService")
                        .WithMany()
                        .HasForeignKey("ProcessingServiceCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcessingCost");

                    b.Navigation("ProcessingService");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.PurchaseContract", b =>
                {
                    b.HasOne("SiagroB1.Domain.Entities.Agent", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentCode");

                    b.HasOne("SiagroB1.Domain.Entities.Warehouse", "DeliveryLocation")
                        .WithMany()
                        .HasForeignKey("DeliveryLocationCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SiagroB1.Domain.Entities.DocType", "DocType")
                        .WithMany()
                        .HasForeignKey("DocTypeCode");

                    b.HasOne("SiagroB1.Domain.Entities.UnitOfMeasure", "FreightUm")
                        .WithMany()
                        .HasForeignKey("FreightUmCode");

                    b.HasOne("SiagroB1.Domain.Entities.HarvestSeason", "HarvestSeason")
                        .WithMany()
                        .HasForeignKey("HarvestSeasonCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SiagroB1.Domain.Entities.LogisticRegion", "LogisticRegion")
                        .WithMany()
                        .HasForeignKey("LogisticRegionCode");

                    b.HasOne("SiagroB1.Domain.Entities.UnitOfMeasure", "UnitOfMeasure")
                        .WithMany()
                        .HasForeignKey("UnitOfMeasureCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("DeliveryLocation");

                    b.Navigation("DocType");

                    b.Navigation("FreightUm");

                    b.Navigation("HarvestSeason");

                    b.Navigation("LogisticRegion");

                    b.Navigation("UnitOfMeasure");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.PurchaseContractAllocation", b =>
                {
                    b.HasOne("SiagroB1.Domain.Entities.PurchaseContract", "PurchaseContract")
                        .WithMany("Allocations")
                        .HasForeignKey("PurchaseContractKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PurchaseContract");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.PurchaseContractBroker", b =>
                {
                    b.HasOne("SiagroB1.Domain.Entities.UnitOfMeasure", "ComissionUm")
                        .WithMany()
                        .HasForeignKey("ComissionUmCode");

                    b.HasOne("SiagroB1.Domain.Entities.PurchaseContract", "PurchaseContract")
                        .WithMany("Brokers")
                        .HasForeignKey("PurchaseContractKey");

                    b.Navigation("ComissionUm");

                    b.Navigation("PurchaseContract");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.PurchaseContractPriceFixation", b =>
                {
                    b.HasOne("SiagroB1.Domain.Entities.PurchaseContract", "PurchaseContract")
                        .WithMany("PriceFixations")
                        .HasForeignKey("PurchaseContractKey");

                    b.Navigation("PurchaseContract");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.PurchaseContractQualityParameter", b =>
                {
                    b.HasOne("SiagroB1.Domain.Entities.PurchaseContract", "PurchaseContract")
                        .WithMany("QualityParameters")
                        .HasForeignKey("PurchaseContractKey");

                    b.HasOne("SiagroB1.Domain.Entities.QualityAttrib", "QualityAttrib")
                        .WithMany()
                        .HasForeignKey("QualityAttribCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PurchaseContract");

                    b.Navigation("QualityAttrib");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.PurchaseContractTax", b =>
                {
                    b.HasOne("SiagroB1.Domain.Entities.PurchaseContract", "PurchaseContract")
                        .WithMany("Taxes")
                        .HasForeignKey("PurchaseContractKey");

                    b.HasOne("SiagroB1.Domain.Entities.Tax", "Tax")
                        .WithMany()
                        .HasForeignKey("TaxCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PurchaseContract");

                    b.Navigation("Tax");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.QualityInspection", b =>
                {
                    b.HasOne("SiagroB1.Domain.Entities.QualityAttrib", "QualityAttrib")
                        .WithMany()
                        .HasForeignKey("QualityAttribCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SiagroB1.Domain.Entities.WeighingTicket", "WeighingTicket")
                        .WithMany("QualityInspections")
                        .HasForeignKey("WeighingTicketKey");

                    b.Navigation("QualityAttrib");

                    b.Navigation("WeighingTicket");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.SalesContract", b =>
                {
                    b.HasOne("SiagroB1.Domain.Entities.Agent", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentCode");

                    b.HasOne("SiagroB1.Domain.Entities.DocType", "DocType")
                        .WithMany()
                        .HasForeignKey("DocTypeCode");

                    b.HasOne("SiagroB1.Domain.Entities.HarvestSeason", "HarvestSeason")
                        .WithMany()
                        .HasForeignKey("HarvestSeasonCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SiagroB1.Domain.Entities.LogisticRegion", "LogisticRegion")
                        .WithMany()
                        .HasForeignKey("LogisticRegionCode");

                    b.HasOne("SiagroB1.Domain.Entities.UnitOfMeasure", "UnitOfMeasure")
                        .WithMany()
                        .HasForeignKey("UnitOfMeasureCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("DocType");

                    b.Navigation("HarvestSeason");

                    b.Navigation("LogisticRegion");

                    b.Navigation("UnitOfMeasure");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.SalesInvoiceItem", b =>
                {
                    b.HasOne("SiagroB1.Domain.Entities.SalesContract", "SalesContract")
                        .WithMany()
                        .HasForeignKey("SalesContractId");

                    b.HasOne("SiagroB1.Domain.Entities.SalesInvoice", "SalesInvoice")
                        .WithMany("Items")
                        .HasForeignKey("SalesInvoiceKey");

                    b.Navigation("SalesContract");

                    b.Navigation("SalesInvoice");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.ShipmentRelease", b =>
                {
                    b.HasOne("SiagroB1.Domain.Entities.PurchaseContract", "PurchaseContract")
                        .WithMany("ShipmentReleases")
                        .HasForeignKey("PurchaseContractKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PurchaseContract");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.ShippingOrder", b =>
                {
                    b.HasOne("SiagroB1.Domain.Entities.StorageAddress", "StorageAddress")
                        .WithMany()
                        .HasForeignKey("StorageAddressKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StorageAddress");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.StorageAddress", b =>
                {
                    b.HasOne("SiagroB1.Domain.Entities.DocType", "DocType")
                        .WithMany()
                        .HasForeignKey("DocTypeCode");

                    b.Navigation("DocType");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.StorageTransaction", b =>
                {
                    b.HasOne("SiagroB1.Domain.Entities.DocType", "DocType")
                        .WithMany()
                        .HasForeignKey("DocTypeCode");

                    b.HasOne("SiagroB1.Domain.Entities.ProcessingCost", "ProcessingCost")
                        .WithMany()
                        .HasForeignKey("ProcessingCostCode");

                    b.HasOne("SiagroB1.Domain.Entities.ShipmentRelease", "ShipmentRelease")
                        .WithMany()
                        .HasForeignKey("ShipmentReleaseKey");

                    b.HasOne("SiagroB1.Domain.Entities.StorageAddress", null)
                        .WithMany("Transactions")
                        .HasForeignKey("StorageAddressKey");

                    b.HasOne("SiagroB1.Domain.Entities.UnitOfMeasure", "UnitOfMeasure")
                        .WithMany()
                        .HasForeignKey("UnitOfMeasureCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SiagroB1.Domain.Entities.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocType");

                    b.Navigation("ProcessingCost");

                    b.Navigation("ShipmentRelease");

                    b.Navigation("UnitOfMeasure");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.StorageTransactionQualityInspection", b =>
                {
                    b.HasOne("SiagroB1.Domain.Entities.QualityAttrib", "QualityAttrib")
                        .WithMany()
                        .HasForeignKey("QualityAttribCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SiagroB1.Domain.Entities.StorageTransaction", "StorageTransaction")
                        .WithMany("QualityInspections")
                        .HasForeignKey("StorageTransactionKey");

                    b.Navigation("QualityAttrib");

                    b.Navigation("StorageTransaction");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.Truck", b =>
                {
                    b.HasOne("SiagroB1.Domain.Entities.State", "State")
                        .WithMany()
                        .HasForeignKey("StateKey");

                    b.Navigation("State");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.WeighingTicket", b =>
                {
                    b.HasOne("SiagroB1.Domain.Entities.Truck", "Truck")
                        .WithMany()
                        .HasForeignKey("TruckCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SiagroB1.Domain.Entities.TruckDriver", "TruckDriver")
                        .WithMany()
                        .HasForeignKey("TruckDriverCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Truck");

                    b.Navigation("TruckDriver");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.ProcessingCost", b =>
                {
                    b.Navigation("DryingDetails");

                    b.Navigation("DryingParameters");

                    b.Navigation("QualityParameters");

                    b.Navigation("ServiceDetails");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.PurchaseContract", b =>
                {
                    b.Navigation("Allocations");

                    b.Navigation("Brokers");

                    b.Navigation("PriceFixations");

                    b.Navigation("QualityParameters");

                    b.Navigation("ShipmentReleases");

                    b.Navigation("Taxes");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.SalesInvoice", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.StorageAddress", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.StorageTransaction", b =>
                {
                    b.Navigation("QualityInspections");
                });

            modelBuilder.Entity("SiagroB1.Domain.Entities.WeighingTicket", b =>
                {
                    b.Navigation("QualityInspections");
                });
#pragma warning restore 612, 618
        }
    }
}
