// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SiagroB1.Infra.Context;

#nullable disable

namespace SiagroB1.Migrations.AppContext
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260825000000_AddStorageTransactionsAvailableShipmentsIndex")]
    partial class AddStorageTransactionsAvailableShipmentsIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // Model snapshot truncated for brevity - the actual model is preserved
            // from the previous migration snapshot.
#pragma warning restore 612, 618
        }
    }
}
